algoritmo "14"
var
X,Y,Z:REAL


inicio
ESCREVAL("==========================================")
ESCREVAL("           LOCADORA DIAS                  ")
ESCREVAL("==========================================")
ESCREVAL(" DIGITE QUANTOS KM VOCE PERCORREU COM O CARRO:")
LEIA(X)
ESCREVAL(" DIGITE A QUANTIDADE DE DIAS QUE VOCE UTILISOU O CARRO:")
LEIA(Y)
Z<-X*0.20+Y*90
ESCREVAL(" O VALOR A SER PAGO SERA:R$",Z)


fimalgoritmo
